---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/docker --version
      register: docker_binaries_test_output
    - debug:
        msg: '{{ docker_binaries_test_output.stdout }}'
